### ISSUE TITLE
Confusion about camera forward axis

### ISSUE THREAD

**Issue by lastbasket** [sony/NeISF#3]
https://github.com/sony/NeISF/blob/e31361bdbd2d5c650420782b7c9247e8e4dad909/mymodules/datasets.py#L283

I think this line refers to the second line of the w2c matrix, how to understand this as the forward camera axis?

**Comment by ligoudaner377** [comment]
Hi @lastbasket 
Thank you for your interest in this project, and sorry for the confusion.
L283 is a simplified implementation that can save some computation, but it is not easy to read.

When converting a vector from the camera coord to the world coord, basically, what you need to do is:
```v_world = v_camera @ c2w.T```
because ```c2w.T = w2c```, so the simplified code is:
```v_world = v_camera @ w2c```

Back to the question, ```[0., 1., 0.]``` is the right axis of the camera in the camera coordinate.
as a result ```[0., 1., 0.] @ w2c```  is the right axis of the camera in the world coordinate.
Does this make sense to you?

**Comment by lastbasket** [comment]
Is the [0., 1., 0.] the camera's up vector? Since I think the order should be x, y, z.

**Comment by ligoudaner377** [comment]
Please refer to this line
https://github.com/sony/NeISF/blob/e31361bdbd2d5c650420782b7c9247e8e4dad909/README.md?plain=1#L188

x,y,z correspond to the down, right, backward direction
so I think [0., 1., 0.] the camera's right axis in the camera coordinate

**Comment by lastbasket** [comment]
![Screenshot from 2024-10-25 15-09-14](https://github.com/user-attachments/assets/d9e7ae72-b4b3-431f-b28f-3782bafa0bd8)
But I think in mitsuba the target basis is horizontal? While in https://github.com/sony/NeISF/blob/e31361bdbd2d5c650420782b7c9247e8e4dad909/mymodules/polarutils.py#L567
the cross-product of wo_wld and cam_axis (right) will result in a vertical target basis.

**Comment by lastbasket** [comment]
https://github.com/sony/NeISF/blob/e31361bdbd2d5c650420782b7c9247e8e4dad909/mymodules/datasets.py#L247-L248
And also I think the pose has been converted to right up back for x, y, z.

**Comment by ligoudaner377** [comment]
Actually, the reason we use [0., 1., 0.] is to follow the implementation of [Mitsuba 3.0](https://github.com/mitsuba-renderer/mitsuba3/blob/2e86e5e013b397391d6a59b09ee8238df03589b4/src/integrators/stokes.cpp#L104)

In addition, the correctness of the renderer has been verified by comparing the results between Mitsuba and our renderer.
(Please see Figure 1 of the [supp.](https://openaccess.thecvf.com/content/CVPR2024/supplemental/Li_NeISF_Neural_Incident_CVPR_2024_supplemental.pdf)

**Comment by lastbasket** [comment]
Yes, that is correct, just wonder if the comment https://github.com/sony/NeISF/blob/e31361bdbd2d5c650420782b7c9247e8e4dad909/mymodules/datasets.py#L283
can be corrected to the up camera axis, since the right axis is misleading.

**Comment by ligoudaner377** [comment]
Sure, a reasonable requirement.
will update it soon

**Comment by Taishi-Ono** [comment]
the commit 9df262c122ade229c7e517371377dec3596c741e solved the issue.
